const TIPO_FUNC_NATIVA = {
    FUNC_TO_LOWER: 'FUNC_TO_LOWER',
    FUNC_TO_UPPER: 'FUNC_TO_UPPER',
    FUNC_LENGTH: 'FUNC_LENGTH',
    FUNC_TRUNCATE: 'FUNC_TRUNCATE',
    FUNC_ROUND: 'FUNC_ROUND',
    FUNC_TYPE_OF: 'FUNC_TYPE_OF',
    FUNC_TO_STRING: 'FUNC_TO_STRING',
    FUNC_TO_CHAR_ARRAY: 'FUNC_TO_CHAR_ARRAY',
}

module.exports = TIPO_FUNC_NATIVA